### ISSUE TITLE
Refactor code around our use of `showInformationMessage` to make sure it's only called once.

### ISSUE THREAD

**Issue by tcg** [tcg/vscode-toggle-settings#5]
I think in *two* spots, we use this code to announce in the UI when settings were toggled *globally*, when a workspace isn't available (trying to be nice in the UI and make sure an end-user would understand what happened):

```
        vscode.window.showInformationMessage(
          "Settings were toggled Globally, for lack of an active Workspace."
        );
``` 

If you look, that's happening inside a loop that updates each setting individually. Ideally, this happens outside of a loop. Making that change/refactor is the scope of this issue.

The docs for `showInformationMessage` don't appear to explicitly say that VSCode will ignore duplicate messages within a certain timeframe... however, that's kind of the behavior I'm seeing. I'm guessing it's doing something like that, because I'm changing ~5 settings at once and only seeing a single instance of that message. Regardless, it's best if we only call it once, if any of the settings updated were updated globally.

**Comment by harshalkh** [comment]
i am on it

**Comment by harshalkh** [comment]
I have created a PR #6 for this issue

**Comment by harshalkh** [comment]
Refactored the code and raised the PR #6
