### ISSUE TITLE
Update the `.gitignore` file to exclude `vsix` files. 

### ISSUE THREAD

**Issue by tcg** [tcg/vscode-toggle-settings#8]
There's currently a `toggle-settings-changes-0.0.1.vsix` file committed to this repo (on accident). 

To prevent this in the future, I'd like to: 

* Remove that file from the repo. 
* Update the `.gitignore` file to make sure that `vsix` files are ignored in future commits. 

I'll leave this open for #hacktoberfest.

**Comment by logiclrd** [comment]
This looks pretty straightforward. :-) I'll take it on.

**Comment by harshalkh** [comment]
i am working on this

**Comment by harshalkh** [comment]
> This looks pretty straightforward. :-) I'll take it on.

You can take this.

**Comment by tcg** [comment]
@harshalkh Thanks for jumping in! Looks like @logiclrd already submitted a pull request. 

I'm extremely grateful to both of you for contributing!

--- 

Closed by https://github.com/tcg/vscode-toggle-settings/pull/9
